from typing import Protocol
from infrastructure.persistence.models import Booking

class BookingRepositoryPort(Protocol):
    def create_booking(self, **kwargs) -> Booking: ...
    def get(self, booking_id: int) -> Booking: ...
    def save(self, booking: Booking) -> Booking: ...
