from typing import Protocol, Iterable
from infrastructure.persistence.models import ServiceCategory, Service

class CatalogRepositoryPort(Protocol):
    # Categories
    def list_categories(self) -> Iterable[ServiceCategory]: ...
    def create_category(self, **kwargs) -> ServiceCategory: ...
    # Services
    def list_services(self, **filters) -> Iterable[Service]: ...
    def create_service(self, **kwargs) -> Service: ...
