from typing import Protocol
from infrastructure.persistence.models import Mission

class MissionRepositoryPort(Protocol):
    def get(self, mission_id: int) -> Mission: ...
    def create_for_booking(self, booking_id: int, freelance_id: int) -> Mission: ...
    def save(self, mission: Mission) -> Mission: ...
