from typing import Protocol

class NotificationPort(Protocol):
    def send_push(self, user_id: int, title: str, body: str, data: dict | None = None) -> None: ...
    def send_email(self, to: str, subject: str, html: str) -> None: ...
    def send_sms(self, to: str, message: str) -> None: ...
