from typing import Protocol
from infrastructure.persistence.models import Payment

class PaymentProviderPort(Protocol):
    def create_intent(self, *, method: str, amount: float, currency: str, idempotency_key: str) -> dict: ...
    def capture(self, provider_ref: str) -> dict: ...
    def refund(self, provider_ref: str, amount: float | None = None) -> dict: ...

class PaymentRepositoryPort(Protocol):
    def create(self, **kwargs) -> Payment: ...
    def get(self, payment_id: int) -> Payment: ...
    def get_by_idem(self, idempotency_key: str) -> Payment | None: ...
    def save(self, payment: Payment) -> Payment: ...
