from typing import Protocol, Optional, Any
from infrastructure.persistence.models import User, Profile

class UserRepositoryPort(Protocol):
    def get_by_username_or_email(self, identifier: str) -> Optional[User]: ...
    def create_user(self, **kwargs) -> User: ...
    def ensure_profile(self, user: User, **kwargs) -> Profile: ...
    def get(self, user_id: int) -> User: ...
