name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: djouman
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports: [ "5432:5432" ]
        options: >-
          --health-cmd "pg_isready -U postgres -d djouman"
          --health-interval 5s --health-timeout 3s --health-retries 20
      redis:
        image: redis:7-alpine
        ports: [ "6379:6379" ]
    env:
      DJANGO_SETTINGS_MODULE: djouman.settings.local
      DB_ENGINE: django.db.backends.postgresql
      DB_NAME: djouman
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: localhost
      DB_PORT: 5432
      CELERY_ENABLED: "false"
      PDF_BACKEND: reportlab
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Lint
        run: |
          ruff check .
          isort --check-only .
          black --check .
      - name: Security (Bandit + Safety)
        run: |
          pip install bandit safety
          bandit -r .
          safety check --full-report || true
      - name: Tests
        run: |
          python manage.py migrate --noinput
          pytest -q
      - name: Build image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          tags: djouman/app:ci
