name: Deploy Production
on:
  workflow_dispatch:
  push:
    tags: [ "v*" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production  # ↔ validation manuelle via GitHub Environments
    steps:
      - uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE }}
          aws-region: ${{ secrets.AWS_REGION }}
      - uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ secrets.ECR_REGISTRY }}/djouman:${{ github.ref_name }}
      - name: Render task def
        run: |
          sed "s|IMAGE_URI|${{ secrets.ECR_REGISTRY }}/djouman:${{ github.ref_name }}|g" ops/ecs-taskdef.json > taskdef.json
      - name: Migrations (manuel avant switch)
        run: |
          aws ecs run-task \
            --cluster ${{ secrets.ECS_CLUSTER }} \
            --task-definition ${{ secrets.ECS_TASKDEF_MIGRATIONS }} \
            --launch-type FARGATE \
            --network-configuration "awsvpcConfiguration={subnets=[${{ secrets.SUBNETS }}],securityGroups=[${{ secrets.SECURITY_GROUP }}]}"
      - name: Deploy
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        with:
          task-definition: taskdef.json
          service: ${{ secrets.ECS_SERVICE }}
          cluster: ${{ secrets.ECS_CLUSTER }}
          wait-for-service-stability: true
